name: docker_ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: simple echo
        run: echo hello_world
      - 
        name: checkout
        uses: actions/checkout@v3
      -
        name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}
      -
        name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      -
        name: build and push
        uses : docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/fastapi-tp:hello-world